version: "3.9"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/my.cnf

  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./slave1/data:/var/lib/mysql
      - ./slave1/my.cnf:/etc/mysql/my.cnf

  mysql-slave-2:
    image: mysql:8.0
    container_name: mysql-slave-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./slave2/data:/var/lib/mysql
      - ./slave2/my.cnf:/etc/mysql/my.cnf
